# Generated by Django 3.2.13 on 2022-09-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test0930', '0002_review_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='img',
        ),
    ]
